### ISSUE TITLE
Point Data Model

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/fellow-central#18]
## Task(s)
- [ ] Fields: assignee, timestamp (when earned), amount, description (why earned)

## Dependencies

#13

**Comment by luiszugasti** [comment]
Wonder if it would be _overkill_ to have a "description" table that just acts as an enumeration of all possible descriptions for earning points

**Comment by luiszugasti** [comment]
I feel like a more concise data model for this would be:
- Assignee (foreign key reference to "User" table)
- Event (foreign key reference to "Event" table)
- TimeStamp (Ok - we can keep this for auditing purposes, and then check if a points entry is valid by referencing Event -> StartTime, EndTime. Otherwise, it's redundant)
- Get rid of Amount, Description (Since we can just reference Event when doing a db lookup, this is just redundancy).

So finally:
- Assignee,
- Event,
- TimeStamp

**Comment by cqvu** [comment]
> I feel like a more concise data model for this would be:
> 
> * Assignee (foreign key reference to "User" table)
> * Event (foreign key reference to "Event" table)
> * TimeStamp (Ok - we can keep this for auditing purposes, and then check if a points entry is valid by referencing Event -> StartTime, EndTime. Otherwise, it's redundant)
> * Get rid of Amount, Description (Since we can just reference Event when doing a db lookup, this is just redundancy).
> 
> So finally:
> 
> * Assignee,
> * Event,
> * TimeStamp

These Points represent points earned by fellows. They don't necessarily need to be associated with an Event because fellows can earn points through other means (discord activity, manual input from admins, winning hackathons, etc...).

**Comment by PawanKolhe** [comment]
Yep. we definitely need the **amount** on the point. As cqvu said, there are many ways to earn points, attending events is just one way to earn points. Points would necessarily have an event attached. So we don't need the event field on points in my opinion.

**Comment by luiszugasti** [comment]
Hmm true, i overlooked that consideration we were making! Alright then Event wont have to be a foreign key, and description can be optional (only add a description if there is no associated event)
