### ISSUE TITLE
Get points for all Pods

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/fellow-central#32]
## Task(s)
- [ ]

**Comment by luiszugasti** [comment]
Ideally, we'd create a new blueprint for all the database views. But for now I'll focus on making a monolithic representation because I don't quite recall how to register blueprints when using run flask app. :)

@boyuan12 maybe you can provide comment on that?

**Comment by luiszugasti** [comment]
Closing because getting points for a single pod and getting points accross all pods are a related database view. Check details at #33.

**Comment by boyuan12** [comment]
What do you mean by registering blueprint?   On Thursday, March 11, 2021, 04:24:35 PM PST, Luis Zugasti ***@***.***> wrote:  
 
 


Ideally, we'd create a new blueprint for all the database views. But for now I'll focus on making a monolithic representation because I don't quite recall how to register blueprints when using run flask app. :)

@boyuan12 maybe you can provide comment on that?

**Comment by luiszugasti** [comment]
This is what I mean: https://flask.palletsprojects.com/en/1.1.x/blueprints/

Sent from my iPhone

On Mar 11, 2021, at 19:00, Boyuan Liu ***@***.***> wrote:

﻿

What do you mean by registering blueprint? On Thursday, March 11, 2021, 04:24:35 PM PST, Luis Zugasti ***@***.***> wrote:




Ideally, we'd create a new blueprint for all the database views. But for now I'll focus on making a monolithic representation because I don't quite recall how to register blueprints when using run flask app. :)

@boyuan12 maybe you can provide comment on that?
